### ISSUE TITLE
SALT indexing: facet value parity:  year/date, author, organization

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul_exhibits_template#49]
We believe the SALTworks "Year" facet is akin to the spotlight "Year" facet but we should double check the algorithm once we have all the data accessioned and indexed.

Steps:
- [x]  all the SALT data accessioned into DOR (then purl) as MODS (waiting for sul-dlss/spotlight#1181)
- [x]  index all the SALT data via spotlight
- [ ]  look at facet counts and values for "Year" in saltworks and spotlight.  look at result sets when particular year is selected.

we should also look at author and organization facet values and make sure things look ok
- [ ]  look at facet counts and values for "Author" in saltworks and spotlight.  look at result sets when particular year is selected.
- [ ]  look at facet counts and values for "Organization" in saltworks and spotlight.  look at result sets when particular year is selected.

Document major discrepancies for project team to review, and present to stakeholders as necessary.

**Comment by cbeer** [comment]
https://github.com/sul-dlss/salt/blob/master/lib/stanford/salt_document.rb#L58-L172

**Comment by peetucket** [comment]
Some notes here: https://consul.stanford.edu/display/SALT/SALT+Migration+Project+Plan+2015 

Basically, some  items that used to be public were marked as private, causing the counts to be slightly lower in some cases.  Also data cleanup by Shelley and Daniel will cause date counts to be different.

**Comment by peetucket** [comment]
The "Organization" facet in the old website was derived from extracted entities (which we do not have preserved anymore).  The "Organization" facet in the new website is coming from the zotero created spreadsheet in the column "corporate_entity", which came from the solr field called "corporateEntity_t".   So we were wrong about the facets in Salt that were extracted from entities before - it was "Organization" and not "Corporate Entity".  The corporate entity facet in the old site is a much better match for our Organization facet, but still off a bit.
