### ISSUE TITLE
SALT: Create redirect rules from saltworks to Feigenbaum exhibit, PURL, and/or stacks

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul_exhibits_template#62]
- [x] determine the URL patterns we want to map
- [x] check with ops team about how they'd like to handle this. I know for "vanity urls", we've piled on new vhosts to sulwebapp* (via the www_proxy_service), but we should confirm that this is a reasonable approach here. (SAR-3011)
- [x] create appropriate apache `RedirectMatch` rules for our URL patterns

**Comment by cbeer** [comment]
In the last 2 weeks, here are the URLs that have been requested (in roughly descending order)

- /catalog.html
- /catalog
- /catalog.atom
- /catalog.rss
- /catalog/email
- /assets/{druid}.jpg
- /assets/{druid}.pdf
- /catalog/druid:{druid}
- /catalog/druid:{druid}.xml
- /assets/{druid}.flipbook
- /catalog/druid:{druid}.dc_xml
- /catalog/druid:{druid}.oai_dc_xml
- /assets/{druid}
- /assets/{druid}/00001.jp2

**Comment by cbeer** [comment]
I'd propose we map:

- /assets/{druid}.pdf
- /catalog/druid:{druid}

and redirect all other requests to the front page of the Feigenbaum exhibit. I don't think it's worth our time mapping old search queries to new search queries, or handling thumbnails or metadata responses that are only support the saltworks application.

**Comment by peetucket** [comment]
I agree, those two mappings are sufficient with all else to the home page.

**Comment by cbeer** [comment]
:ok_hand: SAR-3011 will take care of all of that. When we're ready to migrate, we'll just point saltworks.stanford.edu at the new redirecting alias.
