### ISSUE TITLE
SALT: Create seed pages for Feigenbaum

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul_exhibits_template#63]
- [x] Home page
<img width="623" alt="screen shot 2015-11-01 at 7 45 35 am" src="https://cloud.githubusercontent.com/assets/111218/10869730/8e7aac8a-806c-11e5-88ea-56301caba1e0.png">

- [x] Browse categories (@ggeisler to provide?)

- [x] About pages

**Comment by ndushay** [comment]
@ggeisler @peetucket    is this done?

**Comment by ggeisler** [comment]
I'd say so.
